Translation of Web UI
owntone/owntone-server pull request #1476
Opened 2022-05-20 11:50 UTC by hacketiwack

PR related to Translation of the Web UI #1458

With this PR, the interface has been entirely (hopefully) translated.
However, the language setting is not yet stored because the underlying API does not provide yet a way to store the language. Therefore, this part should be done in another PR.

2022-05-21 07:53 UTC, hacketiwack commented on web-src/vite.config.js
> +const owntoneUrl = process.env.VITE_OWNTONE_URL ?? 'http://192.168.0.9:3689'
This is a mistake. It should remain as it was.
```suggestion
const owntoneUrl = process.env.VITE_OWNTONE_URL ?? 'http://localhost:3689'
```

2022-05-28 07:02 UTC, chme requested changes
Thanks a lot for implementing this feature!

Due to the many formatting changes, the individual files are difficult to review.
Could you please fix the formatting? Running the following command should be enough to fix all of them:

``` bash
npm run format
```

And please drop the changed `index.js` from this PR. (I will do a rebuilt of the web interface after this is merged).

2022-05-29 16:50 UTC, hacketiwack commented on web-src/package.json
> +    "@intlify/vue-i18n-loader": "^3.0.0",
Agree. Corrected. in the last push.

2022-05-29 16:57 UTC, hacketiwack commented on web-src/package.json
> +    "@vue/cli-shared-utils": "^5.0.4",
Agree. Dropped with the latest commit.

2022-05-29 16:58 UTC, hacketiwack commented on web-src/package.json
> +    "vue-cli-plugin-i18n": "~2.3.1"
Agree. Library has been removed in the last commit.

2022-06-03 05:02 UTC, chme approved these changes

2022-06-03 05:03 UTC, merged

2022-06-03 05:04 UTC, chme commented
Looks good to me. Thanks!